In [3]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [4]:
x = np.array([1,1,1,1], dtype=np.int64)
x

array([1, 1, 1, 1])

Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [5]:
X=np.array([[1,2],[3,4]])
mat=np.reshape(X,(2,2))
mat


array([[1, 2],
       [3, 4]])

Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [6]:
A=np.linspace(3,10,50)
A

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [7]:
X=np.array([[1,2,3],[4,5,6]])
y=np.reshape(X,(1,6))
y



array([[1, 2, 3, 4, 5, 6]])

Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [8]:
x=np.arange(1,10)



 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [9]:
A=np.array([[1,2],[3,4]])
print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [10]:
x=np.array([[1,4],[3,1]])
x_sort=np.sort(x,axis=1)
x_sort

array([[1, 4],
       [1, 3]])

Q8 Get the indices that would sort x(as above) along the second axis.

In [11]:
ind_sort=np.argsort(x,axis=1)
ind_sort

array([[0, 1],
       [1, 0]])

Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [12]:
import random
x=np.random.randint(1,10,(2,5))
x

array([[5, 8, 3, 7, 1],
       [3, 5, 5, 3, 1]])

In [13]:
print(np.max(x))
print(np.min(x))
print(np.argsort(x,axis=1))

8
1
[[4 2 0 3 1]
 [4 0 3 1 2]]


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [14]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

Drop rows that contain a missing value. 

Find the correlation between first two columns.

Find the mean,median and standard deviation of column 3.

In [51]:
mean_col=iris_2d.mean(axis=1)
median_col=np.median(iris_2d,axis=1)
std=np.std(iris_2d,axis=1)
print(mean_col[2])  #mean of third column
print(median_col[2])
print(std[2])

2.35
2.25
1.7298843892006195


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [57]:
new_col=[[np.pi*iris_2d[0,2]*np.power(iris_2d[0,1],2)/3]]
iris_2D=np.append(iris_2d,new_col,axis=None)
iris_2D


array([ 5.1     ,  3.5     ,  1.4     ,  0.2     ,  4.9     ,  3.      ,
        1.4     ,  0.2     ,  4.7     ,  3.2     ,  1.3     ,  0.2     ,
        4.6     ,  3.1     ,  1.5     ,  0.2     ,  5.      ,  3.6     ,
        1.4     ,  0.2     ,  5.4     ,  3.9     ,  1.7     ,  0.4     ,
        4.6     ,  3.4     ,  1.4     ,  0.3     ,  5.      ,  3.4     ,
        1.5     ,  0.2     ,  4.4     ,  2.9     ,  1.4     ,  0.2     ,
        4.9     ,  3.1     ,  1.5     ,  0.1     ,  5.4     ,  3.7     ,
        1.5     ,  0.2     ,  4.8     ,  3.4     ,  1.6     ,  0.2     ,
        4.8     ,  3.      ,  1.4     ,  0.1     ,  4.3     ,  3.      ,
        1.1     ,  0.1     ,  5.8     ,  4.      ,  1.2     ,  0.2     ,
        5.7     ,  4.4     ,  1.5     ,  0.4     ,  5.4     ,  3.9     ,
        1.3     ,  0.4     ,  5.1     ,  3.5     ,  1.4     ,  0.3     ,
        5.7     ,  3.8     ,  1.7     ,  0.3     ,  5.1     ,  3.8     ,
        1.5     ,  0.3     ,  5.4     ,  3.4     , 

Run the following loaad command and solve the following questions

In [36]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


Find the count of unique species.

In [72]:
np.unique(iris, return_counts=True, axis=1)

TypeError: ignored

Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

Find the most frequent value of petal length (3rd column) in iris dataset

In [71]:
from collections import Counter
  
def mostCommon(iris):
          
    return [Counter(col).most_common(1)[0][0] for col in zip(*iris)]
array=np.array(mostCommon(iris))
array[2] # most frequent value of 3rd column


b'1.5'